language: node_js
node_js:
  - 12.6.0
cache:
  directories:
    - node_modules
script:
  - npm run test
after_script:
  - cat ./coverage/lcov.info | coveralls
branches:
  only:
    - feature/algoexpert
